In [21]:
!pip install pygame

In [2]:
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline

In [3]:
df = pd.read_csv("Truck_data_Labeled_random_leaders.csv")
df.head()

,years_of_experience,aerodynamics_score,technological_score,Leader
0,4,45,10,1
1,6,29,7,0
2,8,34,9,0
3,5,50,9,1
4,4,19,8,0


In [4]:
leader = df[df.Leader==1]
leader.shape

(1579, 4)

In [5]:
NOT_Leader = df[df.Leader==0]
NOT_Leader.shape

(3421, 4)

In [6]:
X = df[['years_of_experience','aerodynamics_score','technological_score']]
X.head()

,years_of_experience,aerodynamics_score,technological_score
0,4,45,10
1,6,29,7
2,8,34,9
3,5,50,9
4,4,19,8


In [7]:
Y = df.Leader
Y.head()

0    1
1    0
2    0
3    1
4    0
Name: Leader, dtype: int64

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,train_size=0.8)

In [9]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [10]:
model.fit(X_train, Y_train)

LogisticRegression()

In [11]:
x_pred=model.predict(X_test)


In [12]:
model.predict_proba(X_test)
X_test

,years_of_experience,aerodynamics_score,technological_score
1433,2,45,5
160,1,44,5
756,12,29,5
3287,2,42,4
1747,0,22,7
...,...,...,...
2444,3,35,4
178,0,14,4
4065,5,25,3
4547,4,19,4


In [13]:
model.score(X_test,Y_test)

0.91

In [24]:
test = pd.read_csv("test.csv")
test.head()

,years_of_experience,aerodynamics_score,technological_score
0,4,5,10
1,2,19,5
2,5,20,7


In [25]:
model.predict(test)

array([0, 0, 0])

In [26]:
import numpy as np
probs=model.predict_proba(test)
probs

array([[0.99725814, 0.00274186],
       [0.98221585, 0.01778415],
       [0.96601896, 0.03398104]])

In [38]:
arr = []
probs_percent = probs * 100
probs_percent[0][1]
leading_probability = float('-inf')
Truck_num = 0
index = 0
for row in probs_percent:
    print(row[1])
    arr.append(row[1])

sorted(arr, reverse=True)

0.2741862542748329
1.778414761569564
3.3981037041600235


[3.3981037041600235, 1.778414761569564, 0.2741862542748329]

In [39]:
for row in probs_percent:
    #index += 1
    if row[1] > leading_probability:
        leading_probability = row[1]
        Truck_num = index+1
    index += 1

In [44]:
Truck_num = 1

In [45]:
leading_probability

3.3981037041600235

In [46]:
import random

follower_num = random.choice([1, 2, 3])
while follower_num == Truck_num:  # Ensure follower number is different from the predicted number
    follower_num = random.choice([1, 2, 3])
follower_num



3

[0 0 0 0 0]
